In [18]:
import pandas as pd
from sklearn import utils,preprocessing

df=pd.read_csv('Clean_Dataset.csv')
df=df.drop(columns='Unnamed: 0')
df=utils.shuffle(df,random_state=1) # shuffling before splitting into training & evaluation (swl oumaima wsh blan tdar hadi wla la)

#### i wanna see the unique values of each column

for col in df.columns:
    print(col)
    display(df[col].unique())


airline


<StringArray>
['Air_India', 'Indigo', 'AirAsia', 'Vistara', 'SpiceJet', 'GO_FIRST']
Length: 6, dtype: str

flight


<StringArray>
[ 'AI-770',  '6E-161',  'I5-330', '6E-5214',  'UK-814',  'UK-851', 'SG-8169',
  'UK-852',  'UK-877', 'SG-4031',
 ...
 'SG-6018', 'SG-9974',  'G8-405',  'I5-737',  'G8-107', 'SG-9923', 'SG-1058',
 '6E-6613', '6E-6719', '6E-6474']
Length: 1561, dtype: str

source_city


<StringArray>
['Kolkata', 'Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Chennai']
Length: 6, dtype: str

departure_time


<StringArray>
['Night', 'Afternoon', 'Morning', 'Early_Morning', 'Evening', 'Late_Night']
Length: 6, dtype: str

stops


<StringArray>
['one', 'zero', 'two_or_more']
Length: 3, dtype: str

arrival_time


<StringArray>
['Morning', 'Evening', 'Early_Morning', 'Afternoon', 'Late_Night', 'Night']
Length: 6, dtype: str

destination_city


<StringArray>
['Mumbai', 'Kolkata', 'Chennai', 'Hyderabad', 'Delhi', 'Bangalore']
Length: 6, dtype: str

class


<StringArray>
['Economy', 'Business']
Length: 2, dtype: str

duration


array([13.67,  6.08,  8.25,  5.08, 12.5 ,  7.17, 12.25, 14.67, 25.75,
       24.67, 16.42,  5.58,  9.5 , 11.33, 10.17,  4.  ,  7.67, 25.33,
        7.58, 25.17,  5.25, 22.33, 11.83, 12.58, 11.67,  7.  , 10.42,
       13.33,  2.92,  4.25,  8.08, 10.58, 13.17, 11.42,  2.75, 25.25,
       22.25,  6.67,  8.58,  2.25, 15.17, 15.83, 26.42,  5.67,  1.58,
        9.67, 12.92, 14.08, 10.25, 26.  ,  4.33,  9.83, 27.33, 24.33,
       23.17,  8.83,  4.42, 25.92,  9.17, 17.17, 10.75, 19.  , 10.5 ,
       12.17, 15.92, 34.58, 16.17, 14.92, 23.67,  9.58, 15.08, 12.  ,
        2.17, 27.08,  1.92,  7.33, 21.92, 40.67,  5.83, 49.83,  2.67,
       13.83,  4.67, 11.58, 21.25, 24.92,  3.25,  4.75, 11.25,  7.25,
       14.  , 11.5 , 27.17,  2.58,  5.5 , 13.08,  2.33,  7.5 ,  5.  ,
        6.  , 12.67, 23.83, 14.25, 23.  , 11.75,  8.  , 13.92, 28.  ,
        1.83, 23.33, 15.67, 14.42,  7.92, 24.17, 16.  ,  5.42,  5.75,
       26.5 , 12.42,  1.75,  6.25, 13.42,  9.25, 20.42, 29.17, 19.83,
        4.5 , 15.58,

days_left


array([49, 11, 23, 43, 31, 15, 41, 30, 27, 28, 18, 38, 36, 14, 16, 48, 35,
        2, 39, 47,  8, 32,  3, 20, 22, 12,  6, 46, 10,  9, 40, 19, 26, 37,
       21,  7, 25, 44,  1, 13, 45, 34,  4, 33, 17, 24, 42,  5, 29])

price


array([ 6048, 13421,  2836, ..., 38406, 80827, 40862], shape=(12157,))

the columns (features) that should be encoded are:
airline, flights, departure & arrival times, source & destination cities, stops, class

the other ones are already numerical & don't need any more encoding (days_left, price, duration)

i suppose all the data in here is relevant to use in the ML Training

[doc for preprocessing](https://scikit-learn.org/stable/modules/preprocessing.html#encoding-categorical-features)

In [22]:
#### Preprocessing (Encoding)
enc=preprocessing.OneHotEncoder()
enc.fit(df[['airline']])



,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a :class:`scipy.sparse.csr_matrix`,i.e. a sparse matrix in ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",True
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide `.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'error'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide `.",None
,"max_catego